version: '3.8'

services:

  backend:
    build: ..
    ports:
      - 8080:8080
    volumes:
      - ..:/code
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
    depends_on:
      - db

  db:
    image: postgres:latest
    expose:
      - 8000
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: