version: '3.8'

services:

  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ..:/Fastapi_Notes
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    depends_on:
      - db

  db:
    image: postgres:latest
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 25432:5432

volumes:
  postgres_data: