[tool.poetry]
name = "fastapi-notes"
version = "0.1.0"
description = ""
authors = ["Ilya"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = {extras = ["all"], version = "^0.108.0"}
sqlalchemy = {extras = ["all"], version = "^2.0.24"}
pg8000 = "^1.30.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
